name: build

on:
  push:
    branches: ['main', 'master']
    paths: ['vcontrold/**']
    tags:  # Add this line to trigger on tags
      - 'v*'
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    name: ${{ matrix.arch }} build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - aarch64_cortex-a53
          - x86_64
        sdk:
          - openwrt-24.10
          - SNAPSHOT

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build Packages
        uses: kollera/gh-action-sdk@main
        env:
          V: sc
          ARCH: ${{ matrix.arch }}-${{ matrix.sdk }}
          FEEDNAME: vcontrold
          PACKAGES: libxml2 vcontrold
          NO_REFRESH_CHECK: true
          SIGN_KEY_PUB: ${{ secrets.OPENWRT_SIGN_KEY_PUB }}
          SIGN_KEY: ${{ secrets.OPENWRT_SIGN_KEY }}
          FIXUP: 1

      #- name: Upload artifacts
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: ${{ matrix.arch }}-${{ matrix.sdk }}
      #    path: |
      #      bin/packages/${{ matrix.arch }}/vcontrold/*.apk
      #      bin/packages/riscv64_generic/vcontrold/*.apk
      #      bin/packages/${{ matrix.arch }}/vcontrold/*.ipk

      - name: Store packages
        uses: actions/upload-artifact@v4
        with:
          name: vcontrold-${{ matrix.arch }}-packages
          path: bin/packages/${{ matrix.arch }}/**/vcontrold*.ipk

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build  # Ensure this job runs after the build job
    if: startsWith(github.ref, 'refs/tags/')  # Only run this job for tags
    steps:
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}  # Use the tag that triggered the workflow
          name: Release ${{ github.ref }}  # Customize release name
          body: |
            Changes in this release:
            - Add your release notes here.
          files: |
            vcontrold-**-packages
            bin/packages/**/vcontrold/*.apk
            bin/packages/**/vcontrold/*.ipk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided by GitHub Actions

