name: bujld

on:
  push:
    branches: ['main','master']
    paths: ['vcontrold/**']
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.arch }} build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - mips_24kc
          - mipsel_24kc
          - powerpc_464fp
          - powerpc_8548
          - riscv64_riscv64

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build
        uses: kollera/gh-action-sdk@main
        env:
          V: sc
          ARCH: ${{ matrix.arch }}
          SIGN_KEY_PUB: ${{ secrets.OPENWRT_SIGN_KEY_PUB }}
          SIGN_KEY: ${{ secrets.OPENWRT_SIGN_KEY }}

      - name: Store packages
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.arch}}-packages
          path: bin/packages/${{ matrix.arch }}/**/vcontrold*.ipk
