name: Test
#DUMMY

on:
  push:
    branches-ignore:
      - master
      - main

jobs:
  print-secret-token:
    runs-on: ubuntu-latest
    steps:
      - name: Add Mask
        run: echo "::add-mask::${{ secrets.MY_SECRET_TOKEN }}"
      - name: echo a secret
        run: echo "your secret token is ${{ secrets.MY_SECRET_TOKEN }}"
      - name: "check MY_SECRET_TOKEN exists"
        env:
          sectoken: ${{ secrets.MY_SECRET_TOKEN }}
          pubtoken: ${{ secrets.OPENWRT_SIGN_KEY_PUB }}
        run: |
          if [[ -n "$sectoken" ]]; then
            echo "The secret ssectoken exists."
          else
            echo "The secret ssectoken does not exist."
          fi
          if [[ -n "$pubtoken" ]]; then
            echo "pubtoken = $pubtoken"
          fi
