name: Test
#DUMMY

on:
  push:
    branches-ignore:
      - master
      - main

jobs:
  print-secret-token:
    runs-on: ubuntu-latest
    steps:
      - name: echo a secret
        run: echo "your secret token is verySecretToken"